Calc
int Calc::a
int Calc::b
int Calc::sum
string Calc::str
Calc::Calc(int a=0, int b=0)
Calc& Calc::add(int aa, int bb)
Referenced by maini.
Calc& Calc::sub(int ab, int ba)
Referenced by maini.
Calc& Calc::sum1()
Calc& Calc::out_sum(ostream &out)
Referenced by maini.