Screen
typedef string::size_type Screen::index
typedef string::size_type Screen::index
typedef string::size_type Screen::index
string Screen::content
index Screen::cursor
index Screen::width
index Screen::hight
string Screen::contenes
index Screen::lenth
index Screen::height
char Screen::get() const
Referenced by mainClass1, mainClassOverload, mainvis.
const char Screen::get(index wd, index ht) const
Screen Screen::get()
void Screen::get(char)
Screen Screen::move(index, index, char)
Referenced by mainClass1.
char Screen::get() const
const char Screen::get(index, index) const
Screen & Screen::set(char)
Referenced by mainClass1.
Screen & Screen::move(index, index)
Screen& Screen::display(ostream &os)
Referenced by mainClass1.
Screen::Screen(index wd, index ht, const string &str)
void Screen::do_display(ostream &os)